#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

pgrep -x sxhkd > /dev/null || sxhkd &

# checa se existem dois monitores definidos
# MONITORS=$(xrandr --listmonitors | grep Monitors | cut -b 11-)
MONITORS_DP2=$(xrandr --query | grep 'DP-2' | cut -b 6-14)

# caso tenha, executa o setup para dois
# if [[ $MONITORS == 2 ]] ; then
if [[ $MONITORS_DP2 == "connected" ]] ; then
    # xrandr --output HDMI1 --primary --left-of eDP1 --auto &
    bspc monitor eDP-1 -d I II III IV
    bspc monitor DP-2 -d V VI VII VIII
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# https://wiki.archlinux.org/title/bspwm
# https://www.maketecheasier.com/install-configure-bspwm/
# https://github.com/janleigh/dotfiles/blob/master/cfg/bspwm/bspwmrc
# https://github.com/zodd18/dotfiles/blob/master/shared-config/.config/bspwm/bspwmrc
# https://github.com/ayamir/bspwm-dotfiles/blob/master/sxhkd/sxhkdrc
# https://www.vivaolinux.com.br/artigo/Configurando-bspwm-e-dois-monitores    
# https://protesilaos.com/codelog/multihead-bspwm-polybar/
      
      
      
      
      
      
      
      
