#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

## Coloring
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}

COLOR=$(shuf -n1 -e ~/.config/colors/*)
SHORTCOLOR=$(echo $COLOR | sed "s@.*/@@")
xrdb -merge $COLOR

getcolors

pgrep -x sxhkd > /dev/null || sxhkd &

# checa se existem dois monitores definidos
# MONITORS=$(xrandr --listmonitors | grep Monitors | cut -b 11-)
MONITORS_DP2=$(xrandr --query | grep 'DP-2' | cut -b 6-14)

# caso tenha, executa o setup para dois
# if [[ $MONITORS == 2 ]] ; then
if [[ $MONITORS_DP2 == "connected" ]] ; then
    # xrandr --output HDMI1 --primary --left-of eDP1 --auto &
    bspc monitor eDP-1 -d I II III IV
    bspc monitor DP-2 -d V VI VII VIII
else
    bspc monitor eDP-1 -d I II III IV V VI VII VIII
fi

nitrogen --restore & 
picom --config $HOME/.config/picom/picom.conf
# xfce4-power-manager &

## Bspwm configurations
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window_gap 8
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 2
bspc config left_padding 0
bspc config split_ratio          0.52

## Window rules
# remove all rules first
bspc rule -r *:*

$HOME/.config/polybar/launch.sh &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


dunst \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$GREEN" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$FOREGROUND" -cfr "$RED" &
sleep 0.5
# notify-send "Bspwm Loaded" "With $SHORTCOLOR color and $SHORTWALLPAPER wallpaper"

# https://wiki.archlinux.org/title/bspwm
# https://www.maketecheasier.com/install-configure-bspwm/
# https://github.com/janleigh/dotfiles/blob/master/cfg/bspwm/bspwmrc
# https://github.com/zodd18/dotfiles/blob/master/shared-config/.config/bspwm/bspwmrc
# https://github.com/ayamir/bspwm-dotfiles/blob/master/sxhkd/sxhkdrc
# https://www.vivaolinux.com.br/artigo/Configurando-bspwm-e-dois-monitores    
# https://protesilaos.com/codelog/multihead-bspwm-polybar/
# https://github.com/altrgeek/bspwm-polybar/blob/master/.config/bspwm/bspwmrc
# https://github.com/KatsukiAmatsuyu/bspwm_dotfiles
